baseURL = "https://news.ttti.cc/"
languageCode = "zh-Hans"
theme = "moments"
paginate = 10
paginatePath = '.'
 
[params]
    title = "极限快博客"
    signature = "朋友圈风的快博客"
 ## cover = "/img/headbg.jpg"
    name = "南极神"
    avatar = "/img/default_avatar.png"