DefaultContentLanguage = "cn"
baseURL = "https://news.ttti.cc"
title = "极限新闻"
author = "南极神"
copyright = "Copyright © 2008–2023"
languageCode = "cn"
hasCJKLanguage = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "End"
disqusShortname = "NanJi"
# googleAnalytics = "UA-FAKE"
theme = "hugo-theme-tokiwa"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe= true

[params]
bannerFont = "fonts/exampleFont"
description = """
偏听则暗，兼听则明
"""
favicon = "https://gitee.com/nanjishen/Npic/raw/master/img/avatar.jpeg"
useChineseFonts = true

[menu]
  [[menu.main]]
    name = "归档"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "分类"
    url = "/categories/"  
    weight = 2

  [[menu.main]]
    name = "关于"
    weight = 3
    identifier = "about"
    url = "/about/"

[taxonomies]
category = "categories"
tag = "tags"

[social]
home="https://ttti.cc"
telegram="https://t.me/q8886"
qq="http://wpa.qq.com/msgrd?v=3&uin=81489060&site=qq&menu=yes"
weibo="https://weibo.com/nanjishen"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]